name: gitleaks
on:
<<<<<<< HEAD
  pull_request:
    branches: [local]
  push:
    branches: [local]

=======
  push:
    branches: [test]
>>>>>>> 428b412 (testing secret key)
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}